### ISSUE TITLE
Multiple operations in single request

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#126]
**Describe the bug**
When multiple mutations are passed in a single request, only the first operation is completed. The others are silently ignored.

**To Reproduce**
Example Body:
```graphql
deleteFromVoteCollection(
    filter: {postId: {eq: $postId}, profileId: {eq: $profileId}}
  ) {
    ...
  }
insertIntoVoteCollection(
    objects: [{postId: $postId, profileId: $profileId, direction: DOWN}]\
 ) {
    ...
  }
}
```

**Expected behavior**
multiple operations are allowed

**Screenshots**

**Versions:**
 - pg_graphql: `0.1.2`

**Additional context**
https://spec.graphql.org/June2018/#sec-Query
https://spec.graphql.org/June2018/#sec-Mutation

**Comment by mlafeldt** [comment]
@olirice I think there's another angle to this that needs to be addressed for the GraphQL server to work nicely with GraphiQL, Insomnia, and other clients.

Given input like this:

```graphql
mutation insertTodo {
	insertIntoTodoCollection(objects: [{ content: "Hello World" }]) {
		records {
			id
			content
		}
	}
}

mutation deleteTodo {
	deleteFromTodoCollection(filter: {id: {eq: 1} }) {
		records {
			id
		}
	}
}
```

The server will always run `insertIntoTodoCollection` even when selecting the other mutation in GraphiQL. I think this happens because pg_graphql doesn't honor the `operationName` field sent by the client.

Running the first mutation sends this payload:

```
| {"query":"mutation insertTodo {\n\tinsertIntoTodoCollection(objects: [{ content: \"Hello World\" }]) {\n\t\trecords {\n\t\t\tid\n\t\t\tcontent\n\t\t}\n\t}\n}\n\nmutation deleteTodo {\n\tdeleteFromTodoCollection(filter: {id: {eq: 1} }) {\n\t\trecords {\n\t\t\tid\n\t\t}\n\t}\n}\n","operationName":"insertTodo"}
```

Running the second mutation sends this payload:

```
| {"query":"mutation insertTodo {\n\tinsertIntoTodoCollection(objects: [{ content: \"Hello World\" }]) {\n\t\trecords {\n\t\t\tid\n\t\t\tcontent\n\t\t}\n\t}\n}\n\nmutation deleteTodo {\n\tdeleteFromTodoCollection(filter: {id: {eq: 1} }) {\n\t\trecords {\n\t\t\tid\n\t\t}\n\t}\n}\n","operationName":"deleteTodo"}
```

You can see that the only difference is the `operationName` field, which seems to be ignored right now.
