### ISSUE TITLE
Feature Request: persisted queries

### ISSUE THREAD

**Issue by bbigras** [supabase/pg_graphql#16]
# Feature request

https://relay.dev/docs/guides/persisted-queries/

## Is your feature request related to a problem? Please describe.

For http caching.

**Comment by olirice** [comment]
hi, thanks for opening

One of the goals of `pg_graphql` is to be agnostic to everything that isn't
- The SQL schema
- In the user's request context

Persisted queries are great for reducing IO and whitelisting operations but they require exposing a larger public API and managing state that isn't in the request context. For those reasons the feature will most likely be delegated to middleware rather than built directly into the extension

There's a good chance these features will end up in Supabase's GraphQL offering it just may not be part of the postgres extension

**Comment by olirice** [comment]
@rnbokade if you're on the supabase platform the function that handles GraphQL requests in the database is

```sql
create function graphql_public.graphql(
	"operationName" text DEFAULT NULL::text,
	query text DEFAULT NULL::text,
	variables jsonb DEFAULT NULL::jsonb,
	extensions jsonb DEFAULT NULL::jsonb
    )
    returns jsonb
    language 'sql'
as $$
            -- re-route requests to pg_graphql
            select graphql.resolve(
                query := query,
                variables := coalesce(variables, '{}'),
                "operationName" := "operationName",
                extensions := extensions
            );
$$;
```

If you create another plpgsql with the same signature, like `public.graphql`, you could intercept the query and insert any middleware logic you want e.g. 
- whitelist queries
- lookup query from the operationName

So long as that function is exposed via postgrest, you can use it instead of `/v1/graphql` using postgrest's RPC functionality

```
https://<project_ref>.supabase.co/rest/v1/rpc/graphql
```

**Comment by rnbokade** [comment]
How about instead of storing graphql query, somehow computed sql query could be stored... that should be faster right?...
I mean pg_graphql must be at some point in background be generating sql translation and executing it right?
How about writing a new stored procedure called "precompile_and_store_query(graphqlquery : text, storedqueryname :text)"
which compiles graphql to sql/ast/or whatever intermediate format pg_graphql generates (please let me know which format it compiles to as Idk) the stores this representation against query name.

**Comment by olirice** [comment]
> How about instead of storing graphql query, somehow computed sql query could be stored

The compiled SQL is cached using the postgres' prepared statements builtin mechanism. It uses a hash of the GraphQL query as the cache key

> How about writing a new stored procedure called "precompile_and_store_query(graphqlquery : text, storedqueryname :text)"

This functionality isn't something we want to support in pg_graphql proper at this point but if you do decide to tackle it I'd be very interested to hear how you set it up

**Comment by brezinajn** [comment]
For anyone interested, here is a implementation (that needs cleanup) of function that allows persisted queries. Seems to work thought.
``` SQL
create table
  public.graphql_cache (
    query text not null,
    version text not null,
    sha256Hash text not null,
    constraint graphql_cache_pkey primary key (version, "sha256Hash")
  ) tablespace pg_default;

create function public.graphql2(
	"operationName" text DEFAULT NULL::text,
	query text DEFAULT NULL::text,
	variables jsonb DEFAULT NULL::jsonb,
	extensions jsonb DEFAULT NULL::jsonb
    )
    returns jsonb
as $$
declare
	persisted_query graphql_cache%ROWTYPE;
	ver text := extensions->'persistedQuery'->>'version';
	query_hash text := extensions->'persistedQuery'->>'sha256Hash';
	result jsonb;
begin
	if query_hash is not null then
		select * from public.graphql_cache 
			into persisted_query
			where graphql_cache."version" = ver and graphql_cache."sha256Hash" = query_hash
			limit 1;

		if FOUND then
			select graphql.resolve(
					query := persisted_query.query,
					variables := coalesce(variables, '{}'),
					"operationName" := "operationName",
					extensions := extensions
			) into result;

		elseif query is not null then 
			insert into graphql_cache ("sha256Hash", version, query)
			values (
				query_hash,
				ver,
				query
			)
			on conflict ("sha256Hash", version) do nothing;

			select graphql.resolve(
			query := query,
			variables := coalesce(variables, '{}'),
			"operationName" := "operationName",
			extensions := extensions
		) into result;
		end if;
	else 
		select graphql.resolve(
			query := query,
			variables := coalesce(variables, '{}'),
			"operationName" := "operationName",
			extensions := extensions
		) into result;
	end if;
	if result is not null then
		return result;
		else
		return '{"errors":[{"message": "PersistedQueryNotFound"}]}';
	end if;
end;
$$
LANGUAGE plpgsql security invoker;
```
