### ISSUE TITLE
Query don't return all rows

### ISSUE THREAD

**Issue by M4tT3d** [supabase/pg_graphql#187]
**Describe the bug**
There is a default limit (30 nodes) when I run a query on my tables. I tried with apollo, graphql playground, postman and I have also tried to set the `first` parameter to a number that is grater than 30, but I can get max 30 nodes. How can I remove this limit?

**To Reproduce**
I used the following query:
```graphql
query GetAllUsers {
  userCollection(orderBy: { id: AscNullsFirst }) {
    edges {
      user: node {
        id
        email
        name
        surname
      }
    }
  }
}
```
This is not the user table used for the authentication, but it is a table that I have created in the public schema.

**Expected behavior**
The query should return all the rows in the table.

**Versions:**
 - PostgreSQL: 14.1
 - pg_graphql commit ref: ea2ab60

**Comment by olirice** [comment]
The record limit of 30 is not currently configurable.

That restriction makes it more difficult for malicious users to DOS your project since GraphQL's arbitrary nesting can quickly cause result sets to become large and expensive to compute.

There are some longer-term plans to make it adjustable once some other features to help defend against bad actors have landed. For example:
- a maximum recursion depth
- a maximum input/output payload size
- a small `statement_timeout`

but in the short-term, pagination is the recommended approach to retrieving > 30 records

**Comment by stevehenderson** [comment]
This is a very valid reason for limiting the results.    I fully support.

If you come across this issue and pagination isn't a workable option, I have some instructions for self-patching at this [gist.](https://gist.github.com/stevehenderson/8329ca70e1e90c06ee5adea9b4db52f4)
