### ISSUE TITLE
Cannot filter queries on columns of type CHAR

### ISSUE THREAD

**Issue by alex-ketch** [supabase/pg_graphql#192]
**Describe the bug**
Attempting to perform a query over columns of type `CHAR / CHAR(n)` returns empty results.
Changing field type to `VARCHAR` fixes the filtering.

**To Reproduce**
1. Create a table schema with a field of type `CHAR`, e.g. `"iso2" CHAR(2) NOT NULL UNIQUE`.
2. Populate database with data
3. Make a query to verify that data is present.
4. Attempt to add filter to above query
5. See empty results

Sample table schema
```sql
CREATE TABLE IF NOT EXISTS states (
  "name" VARCHAR(255) NOT NULL,
  "iso2" CHAR(2) NOT NULL UNIQUE,
  PRIMARY KEY ("iso2")
);
```

**Expected behavior**
Matching rows are returned.

---

**Screenshots**

**Verify that data is present**
<img width="817" alt="Screenshot 2022-07-09 at 23 47 48@2x" src="https://user-images.githubusercontent.com/1646307/178156377-e3301e0a-3fa9-472d-9308-4ea9d2a12175.png">

**Empty results when attempting to filter above data**
<img width="737" alt="Screenshot 2022-07-09 at 23 55 10@2x" src="https://user-images.githubusercontent.com/1646307/178130656-12658b73-1ddf-4185-b44e-be52a2e6510c.png">

**Comment by olirice** [comment]
that you for reporting, I was able to reproduce the issue

When casting inputs from GraphQL types to PostgreSQL types pg type modifiers are ignored (except for arrays). That is not usually an issue because e.g. `varchar` can handle anything that `varchar(200)` can.

In the `char` case, the casting rule is unusual
```sql
select 'GB'::char -- 'G'
```

to resolve this, we'll need to retain the modifiers when casting.

Your solution of using a `varchar` is a good choice
