### ISSUE TITLE
Allow views to be queried via GQL

### ISSUE THREAD

**Issue by Flambe** [supabase/pg_graphql#205]
# Summary
[summary]: #summary

Make views available in the GQL schema so they can be queried.

# Rationale
[rationale]: #rationale

I have a view with some complex filtering not available via the GQL filter. I would like to be able to query this via GQL like a normal table rather than having to use supabase js.

# Drawbacks
[drawbacks]: #drawbacks

#69 I noticed that views were mentioned as being explicitly excluded in this issue so I presume that there are some drawbacks, but my SQL experience isn't enough to be aware of what these may be?

**Comment by Flambe** [comment]
No problem! I didn't realise that views would have these extra complications so I can definitely understand why they aren't supported yet. Thank you for the detailed response!

**Comment by HTMHell** [comment]
@olirice any news on this? it will be a game changer and will open so many possibilities.

**Comment by olirice** [comment]
No progress yet but coming soon

There are 3 features remaining that I think are required to hit minimal feature-completeness
- globally unique id / select 1 record
- views
- exposing user defined functions

So I aim to get a version of those asap (next few months)

**Comment by olirice** [comment]
Would love some feedback on this thought:

One concern we've had with views is that they take on the role of the creator vs the role of the query-er, which is a security footgun because you're typically creating views with a superuser and superusers ignore row level security. In postgres 15 there is now an option for `security barrier` views which DO use the query user's role. I'm leaning towards making that setting mandatory for view exposed by pg_graphql.
- If RLS is off it should have no impact
- if RLS is on, you'll get the behavior a new user would expect
- its an easy migration for existing views

Other than restricting the feature to pg15, are there any downsides I'm missing?

**Comment by HTMHell** [comment]
Sounds good to me

**Comment by Marviel** [comment]
We're moving to a graphql-focused approach, and would really love this feature!

**Comment by drewbietron** [comment]
Views would be awesome.  Weve ended up heading towards using Graphql with Supabase and our existing db leverages RLS and views pretty heavily so there is a lot of data that just isnt able to be queried without view support.  Glad to see this is on the roadmap!

**Comment by olirice** [comment]
I expect the PR referenced above is going to merge tomorrow. 

If anyone is interested in trying out this feature and providing feedback before the next official release (a few weeks out) please send me your project_ref and I'll have your supabase instance updated.

note that pre-release features may undergo breaking changes before they're released

**Comment by HTMHell** [comment]
> I expect the PR referenced above is going to merge tomorrow.
> 
> If anyone is interested in trying out this feature and providing feedback before the next official release (a few weeks out) please send me your project_ref and I'll have your supabase instance updated.
> 
> note that pre-release features may undergo breaking changes before they're released

I'd like to check it out, thanks!
dhticchigeuhvdgllosl

**Comment by DanielHritcu** [comment]
@olirice I'd be interested to test

```md
buvswfrcgpvlfihlhjrt
```

Thanks!

**Comment by drewbietron** [comment]
> I expect the PR referenced above is going to merge tomorrow. 
> 
> 
> 
> If anyone is interested in trying out this feature and providing feedback before the next official release (a few weeks out) please send me your project_ref and I'll have your supabase instance updated.
> 
> 
> 
> note that pre-release features may undergo breaking changes before they're released

I'd love to try it out. I am currently using Supabase locally only, if I'm able to use the new release locally I'll definitely get it added and try to give feedback. Thank you for tacking on this ability! Huge add 💪🏼

**Comment by olirice** [comment]
@HTMHell `dhticchigeuhvdgllosl` has been updated

@DanielHritcu I don't see a project with ref `zraxiuthzbhwgyjvapfq` could you please double check that is correct?

The docs for how to use views aren't live yet because the release isn't out but you can see the instructions here https://github.com/supabase/pg_graphql/blob/master/docs/views.md

**Comment by drewbietron** [comment]
@olirice - Is this only available in a hosted Supabase environment?  I tried following the installation process for this repo to get access to the views in my local dev environment but I couldn't seem to get it to work.  Maybe I'm missing something obvious 🤷‍♂️ .

Appreciate your work on this!

**Comment by olirice** [comment]
Thanks!

Not yet

When features land on the platform the docs get updated so that's the best place to check to see what's currently available.

We've had a few features land in the last 2 weeks so I'll see about pushing a general off-cycle release this week unless there is significant feedback from testers
