### ISSUE TITLE
add support for Relay.js

### ISSUE THREAD

**Issue by Albert-Gao** [supabase/pg_graphql#209]
very solid GQL support, good job!

any plan for adding a Node() query and universal ID for supporting relay.js?

the hard part might be the latter, in my personal project, i use `users_ksuidValue` for each table for an easy universal ID :D

**Comment by olirice** [comment]
thanks!

> any plan for adding a Node() query and universal ID for supporting relay.js?

We 100% plan to support a GUID. I'll need to do some more looking into the top level `node` query before giving an answer on that one. 

> i use users_ksuidValue for each table for an easy universal ID :D

Nice. A base64 encoded version of that, generic over the primary key, is roughly what we had in mind

**Comment by Albert-Gao** [comment]
thanks for the answer, that would be really really good :)

**Comment by kav** [comment]
We had a similar need and ended up using a v5 UUID over the unique composite which was a great solution, combined with a check if the primary key is already a UUID you might a pretty clean solution without a lot of hassle

**Comment by kav** [comment]
I tried to work around the lack of `node` interface support for relay pagination with a fragment on the root query, since the Query object also supports it and discovered this also doesn't work. Dropping here to save someone the hassle. I can open another issue as well if needed.

```graphql
query HomeScreenQuery($userId: UUID, $filter: ToolsFilter, $first: Int, $after: Cursor) {
  ...ItemCards_query @arguments(filter: $filter, first: $first, after: $after)
}
```
leads to 
> Unknown field 'ItemCards_query_G9cLv' on type 'Query'

Looking at the `@fetchable` directive next since it appears to be designed for this case though looks like the docs are facebook internal...

**Comment by olirice** [comment]
> Looks like node is coming in 0.5.1

yes! a globally unique id name `nodeId` and a `Query.node( nodeId: ID! )` entrypoint are coming in `0.5.1`.

expecting to get it rolled out for existing projects this week

---

resolved by #228

**Comment by kav** [comment]
@olirice have you tested `nodeId` with Relay? It looks suspiciously like Relay expects the field to be `id` and will misbehave if it isn't and needs to be worked around. The convention appears to be to put the `id` field of the database record into `databaseId`  https://github.com/facebook/relay/issues/1682

**Comment by olirice** [comment]
>  have you tested nodeId with Relay?

yes, you can make it work with relay using the `nodeInterfaceIdField` config option so it expects the `node` interface to have `nodeId` vs `id`
```json
{
  "src": "./src",
  "schema": "./src/schema.graphql",
  "language": "typescript",
  "eagerEsModules": true,
  "exclude": ["**/node_modules/**", "**/__mocks__/**", "**/__generated__/**"],
  "schemaConfig": {
    "nodeInterfaceIdField": "nodeId"
  }
}
```
see [ref](https://github.com/facebook/relay/tree/main/packages/relay-compiler#supported-compiler-configuration-options) for all options

I'll likely add a comment directive for `relay_style_ids` that moves `<table.id>` to `collectionId` and reserves `id` for relay, but that is a backwards compatible change that will come a bit later.

> The convention appears to be to put the id field of the database record into databaseId

could you please provide a reference for this? I'd love for there to be a convention to follow but wasn't able to find it in https://github.com/facebook/relay/issues/1682

**Comment by kav** [comment]
I thought it was here https://github.com/facebook/relay/pull/4053, but digging around I can't find a solid reference, looks like just a random blog post or two, so I think you can disregard that bit

**Comment by kav** [comment]
Worth noting because https://github.com/facebook/relay/pull/4053  hasn't been merged relay pagination and refetching doesn't work with fetchable on nodes with the above `schemaConfig.nodeInterfaceIdField`. Working around that via root fragments now but for anyone else who comes along and trips over this you'll see 
`"message": "Invalid input for NonNull type"`
If you try to use `@refetchable` on a Node.
