### ISSUE TITLE
Filters do not handle null values

### ISSUE THREAD

**Issue by sojitko** [supabase/pg_graphql#217]
When using `{ eq: null }` or `{ neq: null }` filters, `IS [NOT] NULL` closure is not being applied. It seems like filter values set to null are ignored when SQL is being constructed. 

Same applies to `in` filter key.

**Comment by olirice** [comment]
Part of the GraphQL spec is that passing `null` to an argument must be treated as though the argument was not provided at all.

One example of what thats necessary is queries with variables. In those cases a null value may be passed to indicate "provide no value for this argument". Or alternatively it could mean "this argument should be explicitly set to the value of null" 

Unfortunately, we have no method for differentiating between the two. This is a broader problem with GraphQL rather than pg_graphql specific so, while it might be counterintuitive, the current behavior is "correct"

For your specific use case, I think the we'd need to support `IS_NULL` in filters.

I've opened a ticket for that here https://github.com/supabase/pg_graphql/issues/218
