### ISSUE TITLE
why limit records under 30?

### ISSUE THREAD

**Issue by juzhiyuan** [supabase/pg_graphql#257]
Hi,

When querying with the `first` attribute, it always returns 30 records maximum. May I know the reason? After searching Google, documentation, and repo issues, no useful information was found.

1. https://github.com/supabase/pg_graphql/blob/master/src/transpile.rs#L757
2. https://github.com/supabase/pg_graphql/blob/master/test/expected/max_page_size.out#L7

**Comment by olirice** [comment]
Sure

We default to 30 when no value is provided because otherwise a `first` or `last` argument would always have to be provided + its standard practice for APIs to implement a default page size

The hard limit of 30 is more opinionated but the goals are:
- to reduce the impact a single query can have on the database to make DOS attacks more difficult
- encourage pagination early in application development

30 was chosen to be consistent with the default page size

**Comment by HTMHell** [comment]
@olirice Is it possible to disable the hard limit for a specific table? I have a table with ~200 categories that I need to fetch. And since I could do that in the regular JS client, does it really matter in terms of DoS attacks?
Also, there is a "max rows" setting in the API settings. Maybe the limit should be taken from there?

**Comment by olirice** [comment]
it is not currently possible to disable that limit without recompiling from source

You make two good points:
- 30 can be restrictive skinny tables for things like categories
- from supabase studios `Max Rows` API setting its reasonable to think that would apply to GraphQL

PostgREST uses an environment variable for its max rows setting, which isn't something we can do for pg_graphql so at minimum I'll reach out to the frontend team to get the setting name changed

In this short term I'd recommend that you continue using pagination, even if it's a little painful for small things like this.

also re-opening the ticket b/c defaults/configurability could probably use some more thought

**Comment by Marviel** [comment]
In our experience, the hard 30 entry limit is a bit restrictive. Would be great if that was the default, but it was configurable. Happy to click a big red "I acknowledge my fate" button :)

**Comment by dvv** [comment]
IMO the hard limit unnecessarily complicates machine-to-machine exchange. I believe `@graphql({"default_limit": 30})` would suffice. Or `@graphql({"default_limit": 30, "hard_limit": 1000})`.
