### ISSUE TITLE
AND | OR | NOT filtering operator support

### ISSUE THREAD

**Issue by AubreyF** [supabase/pg_graphql#271]
Many GQL gateways support AND | OR | NOT operators. For example, here's Dgraph's relevant documentation: https://dgraph.io/docs/graphql/queries/and-or-not/

My particular need is to select records having a BigInt field value within desired boundaries.
Pg_graphql doesn't appear to support the obvious ways this query could be structured:

```
query sampleQuery($gte: BigInt, $lte: BigInt) {
  sampleObject(
    filter: {
      and: [
        { second: { gte: $gte } },
        { second: { lte: $lte } }
      ]
    }
  ) {
    ...
    }
  }
}
```

```
query sampleQuery($gte: BigInt, $lte: BigInt) {
  sampleObject(
    filter: {
      second: { gte: $gte, lte: $lte }
    }
  ) {
    ...
    }
  }
}
```

Does pg_graphql currently support queries of this type, or are there potentially plans for future support?

**Comment by olirice** [comment]
yes extending filters is planned but `AND` and `OR` will be added to the `<TableFilter>` types rather than at the top level l `filter` argument to allow building up conditions equivalent to what is possible with SQL. That is also necessary for backwards compatibility

Based on current plans I expect we'll start looking at this in Q1

**Comment by AubreyF** [comment]
Thanks Oliver!

We'll currently thinking to implement a custom resolver for this particular query. Pleased to hear that integrated AND/OR support is already on your pg_graphql radar.
