### ISSUE TITLE
Allow graphql queries to be sent via GET requests

### ISSUE THREAD

**Issue by Evertt** [supabase/pg_graphql#293]
# Feature request

Allow graphql queries (not mutations) to be sent via GET requests. With the query and the variables both as url-query-parameters.
This feature would allow the backend and the browser (and CDNs in between) to use HTTPs built-in caching . I think it's a no-brainer.

Was inspired by this video:
https://www.youtube.com/watch?v=4lqEXYHPmVk

## Edit

And then of course some design choices need to be made regarding what are the best cache-directives to set for any particular query. Some things are obvious I think, like any query done with an `anon` role can get a `public` cache directive and all queries done with an `authenticated` role need to get a `private` cache directive.

But when it comes to `max-age`, `s-maxage`, `stale-while-revalidate` and other cache directives, I don't know (yet) what would be the best choices. I'm guessing it may be very dependent on the specific query that's being requested. If that's true then we may want to give the developer the option to configure the cache header on a per-query basis?

But for now I think that would be too much. In the short term I think it'd be best to just try to come up with some sane defaults for the most common use-cases. If the developer agrees with the defaults, he can call the graphql endpoint with a GET request to benefit from the cache headers and if the developer does not like the default cache headers then they can still opt-out by calling the graphql endpoint with a POST request.

I hope this all made sense and that you guys see the added value in this.

**Comment by olirice** [comment]
hi @Evertt,

pg_graphql is agnostic to transport, it only provides a SQL function that can be exposed by any method you choose.

I see the appeal of caching queries but there are a couple of challenges:


1)  Cache keys can't be derived automatically

Supabase security is based on role and row level permissions. Row level permissions can run arbitrarily code that can (among other things) reference the current role (anon/authenticated), the current user, make an HTTP call to check the weather, etc. There is no guarantee that a row visible to a user at one second will still be visible after time has elapsed.

Cache control headers help with this, but it would be difficult to configure sane defaults.

2) No good place to implement it 

On the supabase platform, we expose pg_graphql's engine through PostgREST, which reflects an HTTP endpoint based on the shape of the `graphql.resolve` SQL function. In PostgREST, RPC calls are all POST, which (coincidentally) follows GraphQL HTTP convention and makes everything play nicely together.

Since PostgREST's reflection of pg_graphql is default, we don't have convenient levers to pull that would allow us to enable queries over GET. It would require custom middleware, which makes the feature a heavy lift to implement generically.

---

At this point if you're interested in caching I'd recommend using a 3rd party caching solution with supabase graphql underneath, or setting up your own middleware. There might be some info helpful for setting up custom middleware here https://github.com/PostgREST/postgrest/issues/1088#issuecomment-378639127
