### ISSUE TITLE
Graphql schema for non-nullable postgres array allows `NULL` values in array

### ISSUE THREAD

**Issue by Passeriform** [supabase/pg_graphql#308]
**Describe the bug**
I have a column in my table which allows `text[]` type with `NOT NULL` constraint.

My understanding and the current behavior from SQL is that I can't put the value `[ NULL ]` in this column.

Creating graphql schema for this field gives me the type `[String]!` which allows me to pass on `[ null, null ]` as payload. Although postgres disallows to insert this field, the schema should reflect that it isn't allowed.

**To Reproduce**
1. Create a column in a table of type text array
2. Disallow null values (Add NOT NULL constraint)
3. Enable pg_graphql and generate schema
4. Schema will have type `[String]!` instead of `[String!]!`

**Expected behavior**
The graphql schema should rather be `[String!]!` and I shouldn't be able to send `[ null, null ]` as payload.

**Screenshots**
Config of the column in postgres
![image](https://user-images.githubusercontent.com/32395996/215257931-fa35cc0b-a8a3-48e8-bd8a-123a331a890b.png)

Snippet from graphql schema
![image](https://user-images.githubusercontent.com/32395996/215257887-ced1134c-5082-4fa4-a8ae-c5ad92e53d66.png)

**Versions:**
 - PostgreSQL: PostgreSQL 15.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit
 - pg_graphql commit ref: ea2ab60

**Comment by olirice** [comment]
The not null constraint on a SQL table enforces that the whole value is not null but it does not enforce that the elements within the array are not null

Here's an example with a null element in the array of a non-null column

<img width="341" alt="Screenshot 2023-01-28 at 7 27 17 AM" src="https://user-images.githubusercontent.com/12958657/215268814-882e3b39-1337-49fb-aa92-e15b67ec5a30.png">

but if you try to insert a null value as the array:

<img width="646" alt="Screenshot 2023-01-28 at 7 29 32 AM" src="https://user-images.githubusercontent.com/12958657/215268921-1fcece81-3e25-4c9a-a9cc-214d8b5697f6.png">

if you need to enforce that the elements of the array are not null you could use a trigger for that but it would not be reflected in the schema.

Currently there is no way to reliably reflect a type of `[Type!]!` since all SQL types are nullable
