### ISSUE TITLE
Support for offset based pagination

### ISSUE THREAD

**Issue by nuurcodes** [supabase/pg_graphql#320]
Hi, is there support for offset based pagination? I have a few tables on a Dashboard I am building and it would be nice if the user could jump to a specific page. Thanks!

**Comment by olirice** [comment]
We don't currently plan to add `limit`/`offset` pagination because it gets less efficient with each page. Here's a [blog post](https://vladmihalcea.com/sql-seek-keyset-pagination/) discussing the differences between the two.

> could jump to a specific page

thats interesting, I hadn't realized that was a shortcoming. I'll leave this open so it can be revisited

**Comment by olirice** [comment]
Notes for later:
Graphile has an `offset` arg and supports `first`/`offset` or `first`/`offset`/`after`
Hasura has `limit`/`offset` in their native mode but not in Relay mode

**Comment by mifreudenthaler** [comment]
would need this feature as well.
Of course there are numerious advantages of cursors based pagination, but making addressing pages directly is a massive drawback.
We totally love supabse, but the only reason for us to not use supabase in all our projects is the lack of this feature.

graphql.org also mentions both possible solutions.

**Comment by vwkd** [comment]
+1 Support for offset based pagination like in Hasura. This is useful to build pagination based on page numbers. From the amount and total count you can compute the total number of pages, and from the offset you can compute the page number.

Currently, with cursor based pagination this is not possible, because from the cursor alone you can't know where in the result set you are.

**Comment by sia-fl** [comment]
pagination based on page numbers is necessary. The current method I can think of is to enable `totalCount` and then use additional functions to implement related functions when users use paging jumps. It is too uncomfortable.

of course, I also know that the performance of paging directly through offset is very poor. Because of the poor performance, it is not supported at all. I think this is not a 'technical opinion' but a 'prejudice'

I'm stuck now because I know my clients will definitely ask for pagination via offset, which is painful, I don't know rust, and I don't have the ability to fix the plugin myself
