### ISSUE TITLE
How install pg_graphql via SQL with PL/Rust?

### ISSUE THREAD

**Issue by mats16** [supabase/pg_graphql#363]
# Summary
[summary]: #summary

Amazon RDS support `plrust`.
https://aws.amazon.com/blogs/database/build-high-performance-functions-in-rust-on-amazon-rds-for-postgresql/

I want to install `pg_graphql` to RDS, but I can not find how install it via SQL with PL/Rust.

# Rationale
[rationale]: #rationale

Need it to use `pg_graphql` in RDS.

# Design
[design]: #design

Provide instruction to install `pg_graphql` via SQL with PL/Rust.

# Examples
[examples]: #examples

It is an example to install `pgjwt` via SQL with tle.
https://github.com/supabase-community/supabase-on-aws/blob/main/src/supabase-db/sql/init-for-rds/02-tle-pgjwt.sql

# Drawbacks
[drawbacks]: #drawbacks

N/A

# Alternatives
[alternatives]: #alternatives

Amazon RDS supports `pg_graphql` natively.

# Unresolved Questions
[unresolved]: #unresolved-questions

N/A

**Comment by olirice** [comment]
`plrust` is a procedural language for writing rust functions. It'd technically be possible to implement a graphql interface using plrust but it would require a significantly different structure than pg_graphql. The end result would not be able to perform as well due to limitations in plrust around shared memory, inter-function call overhead, etc, though those may relax over time.

Another blocker is that RDS plans to allowlist crates that may be referenced and that list is not currently expected to support all pg_graphql dependencies e.g. `graphql-parser`.

The RDS team has expressed interest in natively supporting pg_graphql and a handful of other pgx based extensions on the platform, but those are very early talks. That's the most likely way we'd see pg_graphql land on RDS

fingers crossed for the future!
