### ISSUE TITLE
Foreign keys on non-null columns should produce nullable GraphQL relationships due to RLS

### ISSUE THREAD

**Issue by bryanmylee** [supabase/pg_graphql#409]
In version 1.2.3, a bugfix was introduced to make relationships non-nullable if the foreign key column is non-nullable.

However due to RLS, it is possible that a non-nullable foreign key column produces a relationship that returns `null`.

My team recently faced this as we're building an access-control system that limits which entities a user can access. e.g. a user might have access to an entity with a non-nullable foreign key field `subsystemId`, but the administrator may disable view access to that specific subsystem. When performing the query:

```gql
fragment X on Component {
  subsystemId
  subsystem {
    id
    name
  }
}
```

...the user will receive `subsystemId: "a5ff110a-4d69-4ea5-af83-d02086e9215f"`, but RLS prevents them from viewing the data on `Subsystem:a5ff110a-4d69-4ea5-af83-d02086e9215f`, resulting in the response:

```
{
  // -- snip --
  "subsystemId": "a5ff110a-4d69-4ea5-af83-d02086e9215f",
  "subsystem": null
}
```

**Expected behavior**
All GraphQL relationships should default to nullable, or a configuration setting should be provided to opt-in to nullable relationships by default.

**Comment by bryanmylee** [comment]
Hold on, some further verification on my end is needed.

**Comment by bryanmylee** [comment]
Just verified that this indeed is the current behavior.

**Comment by olirice** [comment]
great point

we'll have to make it nullable when RLS is enabled

**Comment by bryanmylee** [comment]
Thanks so much for all the great work you've done on `pg_graphql`!

**Comment by olirice** [comment]
Expanding the scope on this to:
- Default all fkey linked relations to to nullable when RLS is enabled
- add a comment directive `@graphql({"nullable": <bool>})` on `columns` and `foreign keys` (including comment directive foreign keys) to allow overriding the default

**Comment by pawarren** [comment]
did we ever add a comment directive @graphql({"nullable": <bool>})? i'm trying 

COMMENT ON CONSTRAINT favorites_user_id_work_id_key ON userspace.favorites IS E'@graphql({"nullable": true})';

and it doesn't seem to register

**Comment by imor** [comment]
@pawarren this hasn't been implemented yet.

**Comment by olirice** [comment]
sorry for the big delay on this one. I initially thought we needed to wait until 2.0 but since returned values aren't validated against the schema this falls neatly into the bugfix category for anyone who's impacted

Once it merges we'll cut a new release for it

**Comment by pawarren** [comment]
Great!

**Comment by fourbytes** [comment]
Did `@graphql({"nullable": <bool>})` end up implemented?

We've got a situation where we have a `party` table with foreign key relationships on two other tables `organisation` and `contact`. The joins are party.id = organisation.id and party.id = contact.id, but since the id column on organisation and party is non-nullable, the relationships in GraphQL on the Party entity are also showing as non-nullable.

This results in an error in Apollo as it expects both contact and organisation fields on party to be not null.

**Comment by olirice** [comment]
@fourbytes what version of pg_graphql are you running?
```
select * from pg_available_extensions where name = 'pg_graphql'
```

Which tables, if any have RLS installed?

Are you sure `party.id = organisation.id` and `party.id = contact.id` are correct? That would imply that the relationships are 1:1 and all of the data could be in a single table

> since the id column on organisation and party is non-nullable, the relationships in GraphQL on the Party entity are also showing as non-nullable. .... expects both contact and organisation fields on party to be not null.

did you mean for one of those to say nullable? that reads like you got what you expected

If you could provide an example SQL schema and a screenshot e.g. from GraphiQL showing the issue that'd help debug

**Comment by fourbytes** [comment]
I'm running `pg_graphql` version **1.5.7** and no tables have RLS installed.

Yes, the relationships are as you described: `party.id = organisation.id` and `party.id = contact.id`. This sets up a one-to-one relationship where a `party` can be either a `contact` or an `organisation`, but not necessarily both.

The issue is that in the generated GraphQL schema, the `Party` type has non-nullable `contact` and `organisation` fields. This implies that both fields are always present, which isn't the case in our data model. As a result, Apollo Client expects both `contact` and `organisation` fields on `Party` to be non-null, leading to errors when one of them is `null`.

Here's a simplified SQL schema to reproduce the issue:

```sql
-- Create the party table
CREATE TABLE party (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kind VARCHAR NOT NULL  -- Indicates whether the party is a 'contact' or an 'organisation'
);

-- Create the contact table
CREATE TABLE contact (
    id UUID PRIMARY KEY,  -- Also a foreign key to party.id
    given_name TEXT,
    family_name TEXT,
    FOREIGN KEY (id) REFERENCES party(id) ON DELETE CASCADE
);

-- Create the organisation table
CREATE TABLE organisation (
    id UUID PRIMARY KEY,  -- Also a foreign key to party.id
    name TEXT NOT NULL,
    FOREIGN KEY (id) REFERENCES party(id) ON DELETE CASCADE
);

-- Insert sample data
-- Party as a contact
INSERT INTO party (id, kind) VALUES ('uuid-contact-1', 'contact');
INSERT INTO contact (id, given_name, family_name) VALUES ('uuid-contact-1', 'John', 'Doe');

-- Party as an organisation
INSERT INTO party (id, kind) VALUES ('uuid-org-1', 'organisation');
INSERT INTO organisation (id, name) VALUES ('uuid-org-1', 'Acme Corp');
```

And here's the resulting GraphQL schema generated by `pg_graphql`:

```graphql
type Party implements Node {
  nodeId: ID!
  id: UUID!
  kind: String!
  contact: Contact!           # Non-nullable
  organisation: Organisation! # Non-nullable
  # Other fields...
}

type Contact implements Node {
  nodeId: ID!
  id: UUID!
  givenName: String
  familyName: String
  # Other fields...
}

type Organisation implements Node {
  nodeId: ID!
  id: UUID!
  name: String!
  # Other fields...
}
```

As you can see, both `contact` and `organisation` fields on the `Party` type are non-nullable (`Contact!` and `Organisation!`). In our data model, since a `Party` is either a `Contact` or an `Organisation`, one of these fields will be `null`. This mismatch causes Apollo Client to throw errors when it encounters a `null` value where it expects a non-nullable field.

Cheers.

**Comment by olirice** [comment]
@fourbytes thank you, great example

I've created a new issue for it #557 as its a slightly different problem

**Comment by alfredosalzillo** [comment]
Have `@graphql({"nullable": <bool>})` been implemented in the end?
