### ISSUE TITLE
User provided default is ignored

### ISSUE THREAD

**Issue by btply** [supabase/pg_graphql#453]
Hi there, I seem to have ran into an issue where variables are not working for the cursor based pagination. When you pass a limit variable in via a graphql query, it returns all rows. If you put a number straight in then it works fine. 

The following returns all rows when it should return 3:

```
  query Units($first: Int = 3) {
    unitsCollection(first: $first) { 
      edges {
        node {
          id
          name
          desc
        }}}}
```

This returns 3 rows as expected:

```
  query Units {
    unitsCollection(first: 3) { 
      edges {
        node {
          id
          name
          desc
        }}}}
```

Tested in GraphiQL on the Supabase website.

**Comment by olirice** [comment]
The issue is coming from the use of a user defined default in the query name
```graphql
  query Units($first: Int = 3) {
```
it looks like this isn't currently supported. In the short term you can get around it by removing the default and passing that value as a variable

Notes for implementor:
https://graphql.org/learn/queries/#default-variables

**Comment by olirice** [comment]
flagging priority as its a spec compliance issue
