### ISSUE TITLE
Stored Procedures are not being displayed as GraphQL Mutations.

### ISSUE THREAD

**Issue by AnujiVarghese** [supabase/pg_graphql#464]
Stored Procedures are not being displayed as GraphQL Mutations.

**Comment by olirice** [comment]
Currently, stored procedures are not intended to be exposed in the GraphQL schema

We haven't explored the implications of allowing user defined transaction control within a pg_graphql request/response cycle and also don't support any top level entrypoints into the graph that return `null` because there's no equivalent GraphQL type unless we choose one at random.

Stored procedure support is not currently planned. Could you provide an example of what you're trying to achieve?

**Comment by olirice** [comment]
closing as inactive

**Comment by AnujiVarghese** [comment]
Thank you for the response @olirice
