### ISSUE TITLE
Return json/jsonb columns as json in response instead of string

### ISSUE THREAD

**Issue by imor** [supabase/pg_graphql#488]
Currently json/jsonb columns are returned as a string. The client has to manually parse the json in the string. Consider return proper json instead to make it easier for the clients to consume.

**Comment by olirice** [comment]
JSON/JSONB fields are string encoded because GraphQL can not be extended except for `String` types. As a result, if you try to input raw JSON in an insert mutation it is syntactically incorrect.

example:
<img width="805" alt="Screenshot 2024-01-25 at 5 20 58 AM" src="https://github.com/supabase/pg_graphql/assets/12958657/235766c5-b90e-4d8b-9e30-312ad34a34ad">

so, when used as an input, our only choice is to string encode the value.

Similarly, when returning JSON you have the same spec error if the returned value is not a string. It isn't quite as visible in that case because client libraries generally don't validate returned data against the schema, but the problem is still present. Additionally, we want our JSON types to be consistent in both inputs and outputs, so if they're string encoded on the way in, they need to be string encoded on the way out.

----

[Hasura does not string encode JSON](https://hasura.io/blog/postgres-json-and-jsonb-type-support-on-graphql-41f586e47536/). To handle the errors described ^, you can only pass JSON inputs via variables on that platform.
When returning values, Hasura inlines the raw JSON. In practice it has few downsides, but it is technical a violation of the spec. 

Postgraphile uses the same string encoded model as pg_graphql

I hope that helps explain the design decisions
