### ISSUE TITLE
Feature Request: Schema extensibility

### ISSUE THREAD

**Issue by tinleym** [supabase/pg_graphql#8]
I couldn't find any references to schema extension in the docs, or an acknowledgment of their absence. I think the possibility to employ schema extension in addition to straight reflection is an important consideration for a developer evaluating this library.

Coming from the PostGraphile universe, I'm curious if there are equivalents to (or endorsed recipes to achieve) the following features:

**Schema extension**
https://www.graphile.org/postgraphile/make-extend-schema-plugin/

**Computed columns**
https://www.graphile.org/postgraphile/computed-columns/

**Custom queries**
https://www.graphile.org/postgraphile/custom-queries/

**Custom mutations**
https://www.graphile.org/postgraphile/custom-mutations/

**Comment by olirice** [comment]
> Computed columns

For this, we'll lean on PostgreSQL's built-in generated columns rather than rolling something new
https://www.postgresql.org/docs/12/ddl-generated-columns.html
these already work but I agree that adding to the docs would be a good idea

> Schema extension

This is on the radar and we'll likely be opening an thread to discuss options once core features on the [roadmap](https://supabase.github.io/pg_graphql/roadmap/) are functional

--

Custom queries and mutations both fall under "functions", that are not currently supported. They're next up on the list once Connection conditions and sorting are in place

**Comment by jgoux** [comment]
Schema extension is the most important feature to me.

I usually split my API following some kind of [CQRS](https://martinfowler.com/bliki/CQRS.html) principles where I defer all my "reads" to the built-in generated schema (including RLS policies for automatic filters!) and my "writes" to microservices (lambda, full-blown server, other GraphQL API) so I can have full control over the business logic.

As a user of both Postgraphile and Hasura, the features I use the most are : 
- Defining Postgres functions to add computed fields based on complex queries including session data (current user) + other tables / views
- Calling a remote service through http and expose it as a custom mutation/query
- Being able to connect the result of a custom query/mutation to the schema's types. For example a `userId` to the column `id` of the `users` table. This one is very important so the frontend can loop back into the graph to warm its cache. It needs to support returning union types to model eventual errors (it's a [best practice](https://blog.logrocket.com/handling-graphql-errors-like-a-champ-with-unions-and-interfaces/))
- Full control over how the final schema is exposed : naming convention, filtering root fields (very important to "close" the graph entry points when using RLS)

🚀
