### ISSUE TITLE
Encrypting original database ID when retrieving

### ISSUE THREAD

**Issue by bossjapzz** [supabase/pg_graphql#93]
# Summary
Encrypting original database ID when retrieving

# Examples
based from pg_graphql: we received the raw string id
<img width="951" alt="Screen Shot 2022-02-21 at 4 06 36 PM" src="https://user-images.githubusercontent.com/100037148/154978161-b462b524-2fcb-4095-8694-2538ed8e4bf8.png">

based from hasura: we received the encrypted id
<img width="850" alt="Screen Shot 2022-02-21 at 4 07 38 PM" src="https://user-images.githubusercontent.com/100037148/154978206-8bcaf8b8-77c8-42db-a25c-358d26744b84.png">

Also notable that the **cursor** from `pg_graphql` has the same format of the **id** from `hasura`
and also the **cursor** of `hasura` has the same format like a Bearer token

**Comment by olirice** [comment]
Not re-encoding the id field is intentional

Re-encoding the primary key field is an opinionated choice that we're not ready to make yet as it has a lot of implications and limits the future directions the API can go without breaking changes.

If you're concerned about data leaking via an auto-incrementing id, a uuid primary key should resolve that issue. There is also an opt-in global ID feature that will be coming after the 0.1.0 release goes out
